services:
  php:
    build: .
    container_name: myapp_php
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: myapp_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: autoprime
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_data: 
